### ISSUE TITLE
Input for missing args?

### ISSUE THREAD

**Issue by eldoy** [ielody/todoing#3]
When you write `td update 1` and don't write a new task, the program asks you for the task with `input` in `update.js`.

Can we have this for everything? If I write just `td` then ask for command (list, create, remove, update, delete) and ask for everything else you need too...

Example:
```
td

1. list
2. create
3. update
4. delete
5. done
> 1
```

and then run list, same for other commands.

**Comment by ielody** [comment]
This will be added in the next version. :)
